name: "Validations"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  verify-json-schem:
    name: "Verify json schema"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: '3.12'

      - name: "Install check-jsonschema"
        run: pip install check-jsonschema

      - name: "Verify enrichment record json schema"
        run: check-jsonschema --schemafile schema/enrichment_record.schema.json data/**/**/*.json
  